name: PHP Site Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y php7.4-fpm
          composer install

      - name: Build and deploy PHP site
        run: |
          php test.php
          mkdir -p public
          cp -r * public/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        id: deployment
        environments:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repository: ${{ github.repository }}
          github_event_name: ${{ github.event_name }}
